# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb2f00a7cb929cc5f1113e1c3d97f32f074dd3bdb541abd9f4b74ac77cd172a9cd3042a6e5af03901938eece84927e15dd030dd91a1590945cc4441a0064c9c1

test:
  secret_key_base: c0043a236a64e94be3335e56dc1fe8eb628d030f6a6676332ce0f0dccb25e4da8e8d70e9d370256dbc6e8259ed11dfdda280f67336dd911390ced54128b82d10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
